name: test-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install dependencies
        run:  apt install libasound-dev -y
              apt install libsndfile-dev -y
      - name: build
        run:  mkdir build
              make pc
