name: test-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: apt-get update -y
      - run: apt-get install -y libavformat-dev
      - run: make pc
  test:
      runs-on: ubuntu-latest
    steps:
      - run: apt-get update -y
      - run: apt-get install -y libavformat-dev
      - run: make test
