name: test-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install dependencies
        run:  sudo apt-cache install libasound-dev
              sudo apt-cache install libsndfile-dev
      - name: build
        run:  mkdir build
              make pc
